import { readPdfText } from "pdf-text-reader"
const pool = require('../mysql/connection')
import { openai } from "../../server.js";

export const processResume = async (req, res) => {
    if (!req.file) {
        return res.status(400).send("No file uploaded");
    }

    const fileBuffer = req.file.buffer;
    const fileUint8Array = new Uint8Array(fileBuffer);
    const resumeText = await readPdfText({ data: fileUint8Array });

    const message = await rateResume(resumeText);

    const user_id = req.params.user_id;

    //Conditional statement that (should) determine whether the upload button will create a new resume entry for a user
    //or if it will update a currently existing resume.
    if (req.params.resume_id) {
        const values = [
            req.params.resume_text
        ]
        const resume_id = req.params.resume_id
        const sql = "UPDATE resume SET resume_text = ? WHERE user_id = ? AND resume_id = ?"
        pool.query(sql, [...values,user_id,resume_id], (err,data) => {
            if(err) return res.json(err)
            return pdfText ? res.status(200).send(pdfText) : res.status(500).send("Error processing resume");
        })
    } else {
        const values = [
            req.params.resume_text,
            req.params.resume_id
        ]
        const sql = "INSERT INTO resume (`resume_text`, `resume_id`) VALUES(?)"
        pool.query(sql,[values], (err,data)=> {
            if(err) return res.json(err)
            return pdfText ? res.status(200).send(pdfText) : res.status(500).send("Error processing resume");
        })
    }
    // If this doesn't work just comment my code and uncomment the next line and it should work like before
    // return pdfText ? res.status(200).send(pdfText) : res.status(500).send("Error processing resume");
}
    return res.status(200).send(message);
}

const rateResume = async (resumeText) => {
    const jobInfo = `ZipApply




















    Full stack developer with Web Analytics
    
    
    
    IntelliPro Group Inc.
    
    
    
    Lehi, UT, USA
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    Employment Type
    Contractor
    
    
    
    
    
    
    
    Compensation
    $42 to $46 per hour
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    Phil
    
    
    Your personal recruiter
    
    
    
    
    
    Can I help with your job search?
    
    
    Get Started
    
    
    
    
    
    
    
    
    Job Description:   Duties:** This is a Hybrid role. Looking for candidate who can go into the office**Location
    preferences:1. Lehi, Utah2. Austin, Texas3. San Jose or San Francisco, CAWe are looking for a hardworking, detailed full
    stack engineer who has proficiency in web analytics. Responsibilities include design and develop of web applications
    that supports informative analytics to help better understand product users and adoption.To be successful in this role,
    you should keep your finger on the pulse of the latest trends on web application design and development and JavaScript
    capabilities.Responsibilities:Detailed understanding of NodeJS, React and similar technologies.Using a variety of tools
    to extract and analyze data generated by online user activity.Working with customer analytics and marketing teams to
    implement Adobe Analytics solutions, develop web application that can streamline workflow process and
    automation.Additional understanding and hands on experience on crafting ETL/ELT pipelines using AWS and Azure Data
    Factory/python is nice to have.Skills:Previous web application development, Adobe Analytics, data warehousing and
    analysis experience. Detailed understanding of NodeJS, React and similar technologies. Javascript and
    Typescript.Familiarity with major web analytics tools, such as Analytics, AEP/CJA, Google Analytics.Strong verbal and
    visual interpersonal skills to present and explain insights.Excellent attention to detail and accuracy.Ability to work
    efficiently with different people in engineering, product management, and creative fields. Ability and willing to learn
    new Adobe technologies in short duration of time.Education:Bachelor’s or master’s degree in computer science, marketing,
    statistics, or other related fields.Powered by JazzHRRICJilAHUo
    
    
    
    
    Report Job
    
    
    
    
    
    
    
    
    
    
    Posted date:
    
    
    21 hours ago
    
    
    
    
    
    
    View all Jobs at IntelliPro Group Inc.`  // Job description goes here

    const chat = await openai.chat.completions.create({
        model: 'gpt-4',
        messages: [{ role: 'user', content: `Here is my resume: ${resumeText}
        And here is the job description: ${jobInfo}
        Please give me a rating of 0-100% of how well my resume matches this job, and why. Be concise.` }],
    });

    const message = chat.choices[0].message.content;
    console.log(message);

    return message;
};
